export const Secrets = {
  PORT: Number(process.env.PORT),
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  MYSQL_HOST: process.env.MYSQL_HOST!,
  MYSQL_PORT: Number(process.env.MYSQL_PORT),
  MYSQL_USERNAME: process.env.MYSQL_USERNAME!,
  MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD!,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE!,
  JWT_SECRET: process.env.JWT_SECRET!,
  REDIS_PORT: Number(process.env.REDIS_PORT),
  REDIS_HOST: process.env.REDIS_HOST!,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD!,
  REDIS_URL: process.env.REDIS_URL!,
  QUEUE_STORE_INDEX: Number(process.env.QUEUE_STORE_INDEX),
  SESSION_STORE_INDEX: Number(process.env.SESSION_STORE_INDEX),
  IDEMPOTENCY_KEYS_STORE_INDEX: Number(
    process.env.IDEMPOTENCY_KEYS_STORE_INDEX,
  ),
  VERIFICATION_CODE_STORE_INDEX: Number(
    process.env.VERIFICATION_CODE_STORE_INDEX,
  ),
  CLOUD_NAME: process.env.CLOUD_NAME!,
  CLOUD_API_SECRET: process.env.CLOUD_API_SECRET!,
  CLOUD_API_KEY: process.env.CLOUD_API_KEY!,
  SOCIAL_AUTH_STORE_INDEX: Number(process.env.SOCIAL_AUTH_STORE_INDEX),
  DEFAULT_IMAGE: process.env.DEFAULT_IMAGE!,
  RESEND_EMAIL_API_KEY: process.env.RESEND_EMAIL_API_KEY!,
  APP_NAME: process.env.APP_NAME!,
  APP_EMAIL: process.env.APP_EMAIL!,
  RATE_LIMIT_PER_SECOND: Number(process.env.RATE_LIMIT_PER_SECOND),
  RATE_LIMIT_PER_MINUTE: Number(process.env.RATE_LIMIT_PER_MINUTE),
};
